### ISSUE TITLE
Online version file has wrong min version

### ISSUE THREAD

**Issue by HebaruSan** [sswelm/PersistentThrust#1]
http://ksp-avc.cybutek.net/version.php?id=666

```json
"KSP_VERSION_MIN":{"MAJOR":0,"MINOR":8,"PATCH":1}}
```

This is promising compatibility with KSP 0.8.1 and later. Based on the forum thread it should be 1.8.0 instead.

![image](https://user-images.githubusercontent.com/1559108/84572986-6240c180-ad63-11ea-96db-e852f5ff2d70.png)

Unfortunately ksp-avc.cybutek.net can't do pull requests; it should be:

```json
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":8,"PATCH":0}}
```

This is messing up the CKAN metadata in KSP-CKAN/NetKAN#7972:

```json
    "ksp_version_min": "0.8.1",
```

Tagging @sswelm since not everybody has GitHub notifications turned on for issues.

**Comment by sswelm** [comment]
ok, I fixed it. Sorry for the mistake

**Comment by HebaruSan** [comment]
Looks good, thanks!
