### ISSUE TITLE
Bug: ModuleManager has 10 errors

### ISSUE THREAD

**Issue by zer0Kerbal** [sswelm/PersistentThrust#2]
> [LOG 15:02:53.623] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to MiningExpansion/Parts/Size1Driver/part.cfg/PART[SMX_Size0Driver]
[ERR 15:02:53.624] Error - Cannot parse variable search when replacing (%) key animationName = #$MODULE[FXModuleAnimateThrottle]/animationName$
[WRN 15:02:53.625] Cannot find key animationName in PART
[ERR 15:02:53.625] Error - Cannot parse variable search when replacing (%) key throttleAnimationName = #$../animationName$
[LOG 15:02:53.625] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to MiningExpansion/Parts/Size2Driver/part.cfg/PART[SMX_Size1Driver]
[ERR 15:02:53.625] Error - Cannot parse variable search when replacing (%) key animationName = #$MODULE[FXModuleAnimateThrottle]/animationName$
[WRN 15:02:53.625] Cannot find key animationName in PART
[ERR 15:02:53.625] Error - Cannot parse variable search when replacing (%) key throttleAnimationName = #$../animationName$
[LOG 15:02:53.632] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/ionArgon-0625/ionArgon-0625.cfg/PART[ionArgon-0625]
[LOG 15:02:53.632] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/ionXenon-0625/ionXenon-0625.cfg/PART[ionXenon-0625]
[LOG 15:02:53.632] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/mpdt-0625/mpdt-0625.cfg/PART[mpdt-0625]
[LOG 15:02:53.633] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/mpdt-125/mpdt-125.cfg/PART[mpdt-125]
[LOG 15:02:53.633] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/mpdt-25/mpdt-25.cfg/PART[mpdt-25]
[LOG 15:02:53.634] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/pit-0625/pit-0625.cfg/PART[pit-0625]
[LOG 15:02:53.634] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/pit-125/pit-125.cfg/PART[pit-125]
[LOG 15:02:53.634] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/pit-25/pit-25.cfg/PART[pit-25]
[LOG 15:02:53.635] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/vasimr-0625/vasimr-0625.cfg/PART[vasimr-0625]
[ERR 15:02:53.635] Error - Cannot parse variable search when replacing (%) key animationName = #$MODULE[FXModuleAnimateThrottle]/animationName$
[WRN 15:02:53.635] Cannot find key animationName in PART
[ERR 15:02:53.635] Error - Cannot parse variable search when replacing (%) key throttleAnimationName = #$../animationName$
[LOG 15:02:53.635] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/vasimr-125/vasimr-125.cfg/PART[vasimr-125]
[ERR 15:02:53.636] Error - Cannot parse variable search when replacing (%) key animationName = #$MODULE[FXModuleAnimateThrottle]/animationName$
[WRN 15:02:53.636] Cannot find key animationName in PART
[ERR 15:02:53.636] Error - Cannot parse variable search when replacing (%) key throttleAnimationName = #$../animationName$
[LOG 15:02:53.636] Applying update PersistentThrust/Patches/ROfix/@PART[*]:HAS[@MODULE[ModuleEnginesFX]:HAS[#EngineType[Electric]]]:NEEDS[!zzzRealFuels] to NearFuturePropulsion/Parts/Engines/vasimr-25/vasimr-25.cfg/PART[vasimr-25]
[ERR 15:02:53.636] Error - Cannot parse variable search when replacing (%) key animationName = #$MODULE[FXModuleAnimateThrottle]/animationName$
[WRN 15:02:53.636] Cannot find key animationName in PART
[ERR 15:02:53.636] Error - Cannot parse variable search when replacing (%) key throttleAnimationName = #$../animationName$

**Comment by sswelm** [comment]
what version of PersistentThrust? I though I fixed this in 1.4.6

**Comment by sswelm** [comment]
@zer0Kerbal is this still a problem in 1.4.6?
