### ISSUE TITLE
Thrust warp stopped - propellant depleted

### ISSUE THREAD

**Issue by Patrykz94** [sswelm/PersistentThrust#5]
Hi.

This message appears when I try to enable TimeWarp while under thrust, even though the probe has fuel.

Here are two clips of what is happening:

[Clip 1](https://youtu.be/2Py560b-pt8)
[Clip 2](https://youtu.be/QDpAKwzU2Ds)

The first clip was from a KRASH simulation so I also tested in a normal flight too.

There seem to be two different behaviours here (regardless whether in KRASH simulation or not). One is that I get the message about propelat being depleted when trying to use timewarp and the other is that the timewarp starts but engines stop (probably the default behaviour). Usually after mashing the timewarp button for a while it just starts going into timewarp and stopping the engine.

The KSP version here is 1.8.1 with mod version 1.7.5 (tried both CKAN and manual installation). I also tested the 1.7.8 pre-release version but that has the same issue (only difference I noticed is it does display the ISP correctly when you right click the engine).

I'm playing with RealismOverhaul, RP-1, Kerbalism and quite a few other mods. Here are the logs: [Google Drive link](https://drive.google.com/drive/folders/1R1y4h9rWmofvvdGX4b5NAxEWEKm9JdTh?usp=sharing)

Please let me know if you need me to do extra testing or clarification.

**Comment by sswelm** [comment]
Seems to me something else has control because it does not register any thrust during normal time (0 micro newton),

**Comment by digiefel** [comment]
Should be fixed with the latest master (that also includes the new UI)

**Comment by Patrykz94** [comment]
@Standecco I just tested the master and can confirm that it is working now.
Thanks for the quick fix 👍
